### ISSUE TITLE
Имя `countTrue` - что это???

### ISSUE THREAD

**Issue by Znack** [ktmn17/game-of-life#13]
Будь, плиз, более избирательным в подборе имен, это отличный пример как никогда нельзя переменные называть.
Обязательно к прочтению глава про имена в книге Совершенный Код Макконнелла.

**Comment by ktmn17** [comment]
+

**Comment by Znack** [comment]
А остальные имена по проекту проверил? Больше ничего подобного точно нет? :)

**Comment by Znack** [comment]
Вот еще нашел гениальное название `model.gameCondition`. Что за кондишен? почему именно так названа?

**Comment by ktmn17** [comment]
done

**Comment by Znack** [comment]
Окей, вроде лучше стало

**Comment by Znack** [comment]
Герман, а ты прочитал главу, которую я в начале ишью написал?
Ладно, один раз увидел этот косяк, удивился, увидев второй раз, но в третий раз кривые имена давать, это уже рецидив.

**Comment by ktmn17** [comment]
Прочитал. Не рецидив, ситуации разные

**Comment by Znack** [comment]
А в чем разница?

**Comment by ktmn17** [comment]
В виде ошибки. В третий раз по мне было понятно к чему переменная относится, но я понял, что к этому построже надо подходить.

**Comment by Znack** [comment]
У тебя всегда была одна и та же ошибка, независимо от того, пристуствовали другие или нет (ты как раз про другие говоришь). У тебя во всех трех случаях не было отношения к своему коду такого, который бы предполагал, что твой код будут внимательно читать, изучать, перерабатывать и поддерживать. Всегда надо писать такой код, который должен быть легким в поддержке твоим коллегой, вне зависимости от того, учебный это проект, где только ты раз в год залазишь, тестовый проект для будущей работы или крупное коммерческое задание.
И каждый модуль (вплоть до каждого метода в каждом классе) надо рассматривать так, что его могут в любой момент дернуть и в другом проекте заюзать - насколько легко он встанет тогда
