### ISSUE TITLE
Разбить тесты на более мелкие

### ISSUE THREAD

**Issue by Znack** [ktmn17/game-of-life#4]
В идеале один тест должен лишь один конкретный небольшой пример использования тестировать. У тебя, например, тестирование отрисовки поля сразу все подряд ассертит. Сделай лучше один describe, а потом в нем тестируй по отдельности создание клеток, потом отдельно, что нужным клеткам дали класс enabled, потом отдельно клики тестируй и тд

**Comment by ktmn17** [comment]
Все тесты пересмотрел
