### ISSUE TITLE
А зачем в `updateCells` два массива?

### ISSUE THREAD

**Issue by Znack** [ktmn17/game-of-life#6]
Возмодно, тут можно все гораздо читабельней и элегантней сделать

**Comment by ktmn17** [comment]
Потому что первый хранит состояние старых клеток, а второй возвращает новое состояние на основе первого. Если использовать один, то он изменяется в процессе выполнения функции и клетки обновляются на его основе, что дает неправльный результат.

**Comment by Znack** [comment]
Здесь поможет такой подход - не надо сначала создавать пустой массив, а потом мутировать каждую его клетку в отдельности, а при вызове метода начинай бегать по старому массиву, сразу на ходу заполняя новый уже нужными значениями. Тебе тут поможет, например, метод .map у массивов, который без изменения старого массива позволяет возвращать новый (тем более соблюдая стандарты далее тебе в любом случае придется на map перейти)

**Comment by ktmn17** [comment]
Не скажу, что элегатней стало, но поменял

**Comment by Znack** [comment]
Давай переоткрывать :)
Стало элегантней, сейчас еще пару штрихов подскажу:
```
  updateCells() {
    let newCells = this.cells.map( (row, i) => {
      return row.map( (cell, j) => {
        let newCell = new Cell();
        newCell.condition = cell.condition;
        let countTrue = this.checkNeighbors(this.cells, i, j);
        if (cell.condition == cell.dead) {
          if (countTrue === 3) newCell.setAlive();
        } else {
          if (countTrue < 2 || countTrue > 3) newCell.setDead();
        }
        return newCell;
      });
    });
    this.cells = newCells;
  }
```
1.Переменная newCells не нужна, можешь сразу в this.cells результат записывать. 

2. так не надо
```
        newCell.condition = cell.condition;
```
Во-первых, менять атрибуты экземпляра из внешнего мира - моветон, сделай уж метод тогда. А в твоем случае вообще модешь в конструктор клетки передавать ее изначальное состояние, будет гораздо более красивое API
3. Ну и проверку лушче тоже через отдельный метод сделать
``` 
cell.condition == cell.dead
```
заменить на метод например isDead()
