### ISSUE TITLE
Зачем создание начальной разметки в index?

### ISSUE THREAD

**Issue by Znack** [ktmn17/game-of-life#7]
я про эту строку: `document.body.innerHTML = pug();`

**Comment by ktmn17** [comment]
done

**Comment by Znack** [comment]
А у тебя какие варианты были,куда положить этот код, помимо конструктора вью? Мне просто хочется узнать, насколько принятое решение было продуманным

**Comment by ktmn17** [comment]
Можно в метод вью и потом вызывать в контроллере

**Comment by Znack** [comment]
И какие у какого подхода преимущества?

**Comment by ktmn17** [comment]
У первого подхода контроллер не нагружаем без необходимости, так как если мы его вызываем, то нам 100% нужна разметка и она рисуется автоматом. У второго более строгий подход, что сама по себе вью ничего не делает, все контролирует контроллер, ну и гибкость добавится, что если все таки не хотим отрисовывать игру, просто не вызываем метод в контроллере.

**Comment by Znack** [comment]
Ага, и ты какой способ выбираешь? Будешь оставлять все таки рендер в конструкторе?

**Comment by ktmn17** [comment]
Еще минус второго подхода, что почти все методы вью зависят от
```
this.gameBoard = document.querySelector('.window__game');
this.numberOfRowsInput = document.querySelector('.window__input');
this.playButton = document.querySelector('.window__button_play');
this.clearButton = document.querySelector('.window__button_clear');
```
Придется это убирать, делать функцию, которую будет навешивать эти значение только после отрисовки. И если пропустить отрисовку, полезут ошибки.

Я бы оставил, как я сделал. Любые методы вью, нужны только после отрисовки. Опять же смысла вызвать вью без отрисовки нету никакого, так что это хорошо, что она обязательно рисуется. Но я так понимаю, ты намекаешься, что нужно второй подход делать.

**Comment by Znack** [comment]
Я не намекаю, что надо второй подход делать, я просто хочу, чтобы у тебя осознанный выбор был, и чтобы ты понимал преимущества каждого. 
У второго подхода преимущество в гибкости и легкой тестируемости, но проблема с усложненным API (теперь надо два метода знать внешнему миру, чтобы работать со вью), плюс вот этот косяк. Кстати этот косяк можно решить - например, в конструкторе не делай вставку через innerHTML, а просто создай виртуальные DOM-узлы, повесь обработчики, а потом по спец методу эти DOM-узлы просто вставишь. Но тут без jquery будет сложнее, должен признать

**Comment by ktmn17** [comment]
Хорошо, оставлю первый

**Comment by Znack** [comment]
окей
