### ISSUE TITLE
Присвоение внутри else ветки тернарного оператора

### ISSUE THREAD

**Issue by Znack** [ktmn17/game-of-life#8]
Я даже когда название ишью писал, понял, что все очень сложно %)
```
this.length.value <= 40 ? true : this.length.value = 40;
```
Вообще в целом всегда старайся как можно более простые конструкции использовать. Помни, первый приоритет хорошего кода не производительность, краткость или что-то другое, а читабельность. Почти всегда лучше пожертвовать немного производтельностью (пока это некритично) и написать чуть больше строк, зато коллеги должны код понимать с минимальных усилий.
тут же у тебя прямо надо заметить такую конструкцию, всмотреться и, если повезет, разобраться, что ты хотел сделать :)

Я кстати так бы и не заметил бы косяка, если бы пайчарм не подсветил:
![image](https://cloud.githubusercontent.com/assets/2928964/21585164/93c17dae-d0ed-11e6-8b37-b4d1e3b583c6.png)

**Comment by ktmn17** [comment]
done
